[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/kp"
  to = "/.netlify/functions/generate-kp"
  status = 200

[[redirects]]
  from = "/api/contract"
  to = "/.netlify/functions/generate-contract"
  status = 200

[[redirects]]
  from = "/api/lookup/company"
  to = "/.netlify/functions/lookup-company"
  status = 200

[[redirects]]
  from = "/api/lookup/bank"
  to = "/.netlify/functions/lookup-bank"
  status = 200

[[redirects]]
  from = "/api/backend-url"
  to = "/.netlify/functions/backend-url"
  status = 200
